/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.5 and Signal Processing Toolbox 8.1.
 * Generated on: 06-Jan-2022 16:45:12
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 11
 * Stable            : Yes
 * Linear Phase      : Yes (Type 3)
 */

/* General type conversion for MATLAB generated C-code  */

#include "tmwtypes.h"
typedef     double    real64_T;
/* 
 * Expected path to tmwtypes.h 
 * D:\MATLAB\extern\include\tmwtypes.h 
 */
const int lplen = 11;
const real64_T lpbuf[11] = {
   -0.01941546713502,-6.595745361909e-16,  -0.1162343111882,-8.445605811155e-16,
     -0.597183960715,                 0,    0.597183960715,8.445605811155e-16,
     0.1162343111882,6.595745361909e-16,  0.01941546713502
};
